#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm~all
rm -rf 0 boundaries fieldMeasurements constant/polyMesh/boundary constant/polyMesh/cellZones constant/polyMesh/faces constant/polyMesh/neighbour constant/polyMesh/owner constant/polyMesh/points log* ./{[1-9]*,-[1-9]*,*.xml,ParaView*,paraFoam*,*.foam} > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
