#!/bin/bash

source $HOME/OpenFOAM/OpenFOAM-2.4.0-MNF/etc/bashrc
case1Dir=${PWD}/equilibriumWaterCube_1
case2Dir=${PWD}/equilibriumWaterCube_2
numCPU=2

# Console output to log file
#mpirun -np ${numCPU} mdFOAM -case ${case1Dir} -parallel -coupled : -np ${numCPU} mdFOAM -case ${case2Dir} -parallel -coupled &> coupledRun.log

# Console output to console
mpirun -np ${numCPU} mdFOAM -case ${case1Dir} -parallel -coupled : -np ${numCPU} mdFOAM -case ${case2Dir} -parallel -coupled
