#!/bin/bash

source $HOME/OpenFOAM/OpenFOAM-2.4.0-MNF/etc/bashrc

# clean case 1
cd equilibriumWaterCube_1
./cleanCase
cd ..

# clean case 2
cd equilibriumWaterCube_2
./cleanCase
cd ..

# clean case 3
cd equilibriumWaterCube_3
./cleanCase
cd ..

