#!/bin/bash

source $HOME/OpenFOAM/OpenFOAM-2.4.0-MNF/etc/bashrc
case1Dir=${PWD}/equilibriumWaterCube_1
case2Dir=${PWD}/equilibriumWaterCube_2
case3Dir=${PWD}/equilibriumWaterCube_3
numCPU=2

application=mdFoamPlus

# Console output to log file
#mpirun -np ${numCPU} ${application} -case ${case1Dir} -parallel -coupled : -np ${numCPU} ${application} -case ${case2Dir} -parallel -coupled : -np ${numCPU} ${application} -case ${case3Dir} -parallel -coupled &> coupledRun.log

# Console output to console
mpirun -np ${numCPU} ${application} -case ${case1Dir} -parallel -coupled : -np ${numCPU} ${application} -case ${case2Dir} -parallel -coupled : -np ${numCPU} ${application} -case ${case3Dir} -parallel -coupled
