#!/bin/bash

dsmcDir=${PWD}/dsmcDomain
mdDir=${PWD}/mdDomain

dsmcSolver="dsmcFoamPlus"
mdSolver="mdFoamPlus"

# Console output to files (1 per rank, so file .1.0 output from dsmcDomain, file .1.1 output from mdDomain)
mpirun --output-filename Logs/coupledOutput -np 1 ${dsmcSolver} -case ${dsmcDir} -coupled : -np 1 ${mdSolver} -case ${mdDir} -coupled
