#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication dsmcInitialise
runApplication `getApplication` &

echo "The simulation is now running, its progress can be viewed by typing 'tail -f log.dsmcFOAM' and 'gnuplot monitor'. Once steady state is achieved, the resetAtOutput option(s) in system/fieldPropertiesDict should be changed to 'off' to begin the averaging process." &

# ----------------------------------------------------------------- end-of-file
