#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wclean $makeType general
wclean $makeType potentials
wclean $makeType polyCloud
# wclean $makeType molecularMeasurements
# wclean $makeType molecule

# ----------------------------------------------------------------- end-of-file
