#!/bin/sh

printUsage () {
cat << EOF
   Usage: $0 
   Applies wclean to all utilities
EOF
}

if ! [ $# -eq 0 ] ; then
    printUsage
    exit 1
fi


#----------------------------------------------------------------------

clean

cases="mdPolyFoam"

for case in $cases
do
  echo ""
  cd $case
    wclean
  cd ../
done
