#!/bin/bash

dsmcDir=${PWD}/dsmcDomain
mdDir=${PWD}/mdDomain

dsmcSolver="dsmcFoamPlus"
mdSolver="mdFoamPlus"

numCPU=2 #MPI ranks per domain (2 domains = 4 ranks in total)

# Console output to files (1 per rank, so file .1.0 output from dsmcDomain, file .1.2 output from mdDomain)
mpirun -np ${numCPU} --output-filename Logs/coupledOutput ${dsmcSolver} -case ${dsmcDir} -parallel -coupled : -np ${numCPU} ${mdSolver} -case ${mdDir} -parallel -coupled
