#!/bin/bash

dsmcDir=${PWD}/dsmcDomain
mdDir=${PWD}/mdDomain

dsmcSolver="dsmcFoamPlus"
mdSolver="mdFoamPlus"

numCPU=1 #MPI ranks set to 1 for each domain

# Console output to files (1 per rank, so file .1.0 output from dsmcDomain, file .1.1 output from mdDomain)
mpirun -np ${numCPU} --output-filename Logs/coupledOutput ${dsmcSolver} -case ${dsmcDir} -coupled : -np ${numCPU} ${mdSolver} -case ${mdDir} -coupled
