#!/bin/bash

dsmcDir=${PWD}/dsmcDomain
mdDir=${PWD}/mdDomain

dsmcSolver="dsmcFoamPlus"
mdSolver="mdFoamPlus"

numCPUDSMC=4
numCPUMD=4

# Console output to files (1 per rank, so file .1.0 output from dsmcDomain, file .1.2 output from mdDomain)
mpirun --output-filename Logs/coupledOutput -np ${numCPUDSMC} ${dsmcSolver} -case ${dsmcDir} -parallel -coupled : -np ${numCPUMD} ${mdSolver} -case ${mdDir} -parallel -coupled
