#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1

cleanCase

if [ -d "fieldMeasurements" ]; then
  rm -rf fieldMeasurements
fi

if [ -d "boundaries" ]; then
  rm -rf boundaries
fi

if [ -f "constant/polyMesh/boundary" ]; then
  rm -f constant/polyMesh/boundary
fi

# ----------------------------------------------------------------- end-of-file
