#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication dsmcInitialise
runApplication decomposePar
runParallel dsmcFoamPlus 4


# ----------------------------------------------------------------- end-of-file
