#!/bin/sh

printUsage () {
cat << EOF
   Usage: $0 
   Applies wmake to all utilities
EOF
}

if ! [ $# -eq 0 ] ; then
    printUsage
    exit 1
fi


#----------------------------------------------------------------------

clean

cases="createWeightField  deleteMolecules  mapLagrangianFields  mapTwoLagrangianFields  mdInitialiseField  mdInitialiseInExistingField  quickMapLagrangianFields  reconstructXmol"

for case in $cases
do
  echo ""
  cd $case
  echo "wmake $case"
  wmake
  cd ../
done
